language: python
matrix:
  include:
  - python: 3.6
    dist: xenial
    env: TOXENV=django3.0
  - python: 3.7
    dist: xenial
    env: TOXENV=django3.0
  - python: 3.8
    dist: xenial
    env: TOXENV=django3.0
install:
  - pip install tox
script:
  - tox
